networks:
  backend:
    driver: bridge

services:
  web:
    build:
      context: ./tedxlublin
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    container_name: tedxlublin_web
    environment:
      - APP_ENV=dev
    restart: always
    volumes:
      - type: bind
        source: ./tedxlublin
        target: /www
      - static_volume:/home/www/tedxlublin/staticfiles
    networks:
      - backend
        
  postgres:
    image: postgres:latest
    container_name: tedxlublin_pg_database
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tedxlublin_pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./.env.dev
    restart: always
    networks:
      - backend


volumes:
  static_volume:
  postgres_data:
